### ISSUE TITLE
Interlocks, infinite "pending"

### ISSUE THREAD

**Issue by Tramort** [buildbot/buildbot#3119]
Buildbot 0.9.5 from pypi
Little code to reproduce:

```
test_lock = util.WorkerLock("test_lock", maxCount=1)
c["builders"] = []

all_factory =  util.BuildFactory()
for i in range(1,4):
    factory = util.BuildFactory()
    factory.addStep(steps.ShellCommand(
        command=["sleep", str(10)], # bug
        #command=["sleep", str(10 + i)],  # no bug
        locks=[test_lock.access("counting")]
    ))

    c["builders"].append(util.BuilderConfig(name="test" + str(i), factory=factory, workernames=["build-worker"]))

all_factory.addStep(steps.Trigger(name="trigger test", schedulerNames=["test_force"]))

c['schedulers'] = [schedulers.Triggerable(name="test_force", builderNames=["test1", "test2", "test3"]),
                   schedulers.ForceScheduler(name="force_all", builderNames=["test all"])]
c["builders"].append(util.BuilderConfig(name="test all", factory=all_factory, workernames=["build-worker"]))

```
What to do:
run the "test all" builder via web-ui

**What expect:**
All "test" builders would finish correctly one by one.

**What have:**
last builder stay in infinite "pending" and can not be stopped.

master twistd.log, when I try to stop via web-ui:
```
2017-04-17 14:52:03+0300 [_GenericHTTPChannelProtocol,11,127.0.0.1] while invoking <bound method Build.controlStopBuild of <Build test2 number:6 results:success>>
	Traceback (most recent call last):
	  File "/home/maxim/Projects/tests_dev/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	  File "/home/maxim/Projects/tests_dev/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/maxim/Projects/tests_dev/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/data/builds.py", line 128, in actionStop
	    dict(reason=kwargs.get('reason', args.get('reason', 'no reason'))))
	  File "/home/maxim/Projects/tests_dev/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/mq/simple.py", line 47, in produce
	    qref.invoke(routingKey, data)
	--- <exception caught here> ---
	  File "/home/maxim/Projects/tests_dev/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/mq/base.py", line 55, in invoke
	    x = self.callback(routing_key, data)
	  File "/home/maxim/Projects/tests_dev/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/process/build.py", line 539, in controlStopBuild
	    return self.stopBuild(**params)
	  File "/home/maxim/Projects/tests_dev/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/process/build.py", line 555, in stopBuild
	    self.currentStep.interrupt(reason)
	  File "/home/maxim/Projects/tests_dev/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 735, in interrupt
	    lock.stopWaitingUntilAvailable(self, access, d)
	  File "/home/maxim/Projects/tests_dev/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/locks.py", line 181, in stopWaitingUntilAvailable
	    assert (owner, access, d) in self.waiting
	exceptions.AssertionError: 
```

**Suggestions**

buildbot/locks.py:
```
    def claim(self, owner, access):
        """ Claim the lock (lock must be available) """
        debuglog("%s claim(%s, %s)" % (self, owner, access.mode))
        assert owner is not None
        assert self.isAvailable(owner, access), "ask for isAvailable() first"

        assert isinstance(access, LockAccess)
        assert access.mode in ['counting', 'exclusive']
        self.waiting = [w for w in self.waiting if w[0] != owner]
        self.owners.append((owner, access))
        debuglog(" %s is claimed '%s'" % (self, access.mode))
```
`[w for w in self.waiting if w[0] != owner]` might remove more then one owner

**Comment by jlquinn** [comment]
I'm having the same issue in 0.9.10.  I have 2 different builders now stuck and don't know how to unlock them.

**Comment by chapuni** [comment]
Deadlocks in buildsteps should be fixed in v0.9.12.

**Comment by jlquinn** [comment]
Updating to 0.9.12 and restarting fixed the jobs for me.  I just didn't know if it was due to restart or the updated code.

**Comment by krf** [comment]
@chapuni Which commit(s) fixed the issue?

**Comment by tardyp** [comment]
@krf this PR is fixing one deadlock with the locks: https://github.com/buildbot/buildbot/pull/3650

**Comment by angeloudy** [comment]
We are running 0.9.15 and still having this issue. Is there a way to cancel the pending builds, restart didn't work for me.

**Comment by p12tic** [comment]
I think #3650 has fixed this issue. I haven't seen any lock related issues in the last year. The fact that restart doesn't work means that this is likely another issue.
