### ISSUE TITLE
Workers configured_on gets corrupted over time

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3981]
After a certain amount of time, the database does not reflect properly the configuration of the workers.

This leads to two UI issues:
#3956 #3970 

The root cause of those ui issues is that configured_on is empty.

![image](https://user-images.githubusercontent.com/109859/37081827-f8e6c4ba-21ea-11e8-9867-5f30e00b26cb.png)

Need to investigate why.

**Comment by tardyp** [comment]
reconfigure does not fix the state, but restart does.

**Comment by aj062** [comment]
Would be great if the fix can make it to Buildbot 1.1.0

**Comment by tardyp** [comment]
@aj062 I carefully the diff between 0.9.15 and 1.0.0:
https://github.com/buildbot/buildbot/compare/v0.9.15...v1.0.0?expand=1

I can't find any change in the files related to worker configuration. Are you sure the problem wasn't present in 0.9.15?

I would appreciate any help or investigation at least on how to reproduce quickly.
For now I have no clue how to fix it, so I will release 1.0.1 without a fix :-(

**Comment by chrwen-omicron** [comment]
@tardyp as I mentioned in #3970 I'm pretty sure this problem wasn't there in 0.9.13 if this helps.

**Comment by aj062** [comment]
@tardyp By the way, would the "empty configured_on key" impact only the UI, or it can impact the actual builds, scheduling etc. as well?
(I haven't noticed any other problem, but would be good to know in case there is any other related issue)

**Comment by tardyp** [comment]
no configured_on key is just informative for the UI.

**Comment by irhough** [comment]
FWIW, my production 0.9.12 installation has never demonstrated this problem.  My dev installation definitely did starting at 1.0.0, and still does at 1.1.0.  The builders list seems to go empty inevitably, after a few days or so.  Restarting aways clears it back up.  I haven't been able to reliably trigger the condition.

I'm happy to leave some instrumentation/logging in my dev installation to gather data, but I don't know what to do...

**Comment by seankelly** [comment]
This bug is definitely present in 0.9.15. I don't recall seeing it in the previous version we used, 0.9.7.

**Comment by tardyp** [comment]
@irhough in your dev env, does it just triggers without actions (reload, build, etc). Is this something that gets triggered by a cleanup timer?

0.9.14=>0.9.15 definitly has worker actions code. I carefully re-reviewed this, but it doesn't touch the configured_on columns.

**Comment by irhough** [comment]
@tardyp I haven't been able to single out any particular action.  The last time it happened, for example, I'd done a fresh restart on 03/21, run two test builds, then left for the day.  I didn't look at it again until 3/23.  In the intervening period, the only thing that appears in the twistd.log are a bunch of "Timing out client" messages and one "doing housekeeping for master" messages.  I've seen that pattern before, and wondered if it was the housekeeping step...  But the housekeeping step runs at other times without any effect on the builders list.

**Comment by tardyp** [comment]
"doing housekeeping for master" is certainly a reason for worker deconfiguration.

https://github.com/buildbot/buildbot/blob/master/master/buildbot/data/workers.py#L189
via
https://github.com/buildbot/buildbot/blob/master/master/buildbot/data/masters.py#L139

Could you please raise an exception in this method to see where it comes from?

Note that print_stack is not enough, twisted exception handling now has some tricks in order to unfold inlineCallbacks, which is not the case for print_stack

**Comment by tardyp** [comment]
I think I found the issue:

housekeeping is forced once a day, according to:
https://github.com/buildbot/buildbot/blame/master/master/buildbot/master.py#L209
forcing it once a day is not correct as housekeeping force worker deconfiguration.

but.. there was a bug, which was fixed recenty:
https://github.com/buildbot/buildbot/commit/81bcf60a538b7c37a0c6f0358007c52380faaacd

Will submit a PR soon

**Comment by irhough** [comment]
Yep, I think that's it.  I put the exception in, but noticed that it triggered on startup, which didn't seem like it was going to be helpful.  While poking around further, I saw that the housekeeping method is run at startup and shutdown, but also every day at the same time as the last startup.  Because this is a dev installation of buildbot, I restart it frequently...  But the times it's left alone long enough for the daily housekeeping to trigger seem to correspond to when I've noticed the builders list problem.

Thanks for the help!

**Comment by aj062** [comment]
Still facing this issue on one of our large buildbot instance running Buildbot 1.1.1 (other smaller buildbot instances are fine).

Probably another root-cause causing same issue.

**Comment by aj062** [comment]
> Still facing this issue on one of our large buildbot instance running Buildbot 1.1.1 (other smaller buildbot instances are fine).
> 
> Probably another root-cause causing same issue.
> 

@tardyp So, I am able to consistently reproduce this now. It happens for multi-master. Filed https://github.com/buildbot/buildbot/issues/4059 with the details.
