### ISSUE TITLE
util.ChoiceStringParameter resets immediately after selection

### ISSUE THREAD

**Issue by vit9696** [buildbot/buildbot#7772]
Given a form with the following parameter:

```py
param_test = util.ChoiceStringParameter(
    name='test',
    multiple=True, strict=True,
    choices=['a', 'b', 'c'], default=['a', 'b', 'c'],
)
```

Selecting any value in `test` results in immediate deselection of all the values. Tested in Safari and Firefox. This is a regression from React migration. Web inspector shows that the issue manifests itself somewhere inside the `change` JavaScript event.

**Comment by tdesveaux** [comment]
Pretty sure this is fixed in master by #7571, but it wasn't backported

**Comment by vit9696** [comment]
Thank you! Any chance for this to appear in 4.0.2 and any schedule for 4.0.2? This is a rather problematic issue for us.

**Comment by tdesveaux** [comment]
In case you didn't see, it's planned to be backported https://github.com/buildbot/buildbot/issues/7804#issuecomment-2227123936

**Comment by vit9696** [comment]
I have just upgraded to buildbot 4.0.2, but the issue is still present. Whenever I choose any items, they are reset immediately to an empty list.

**Comment by cherrymcgerry** [comment]
We are seeing the same issue still as well on buildbot 4.0.2.

**Comment by hmoffatt** [comment]
I also see this in 4.0.2.

**Comment by p12tic** [comment]
Some of backports to 4.0.2 were incorrect, please test 4.0.3.

**Comment by hmoffatt** [comment]
> Some of backports to 4.0.2 were incorrect, please test 4.0.3.

Unfortunately it's still not working.

**Comment by vit9696** [comment]
Tested, still broken.

**Comment by vit9696** [comment]
Tested, works on 4.1.0. Most likely 4.0.x is still broken.

**Comment by hmoffatt** [comment]
Thanks, looks good on 4.1.0 for me.
